export const sampleProducts = [
  { id: '1', name: 'TPC 5KVA Online UPS', slug: 'tpc-5kva-online-ups', category: 'ups-systems', price: 85000, sale_price: 72000, stock: 15, description: 'High-performance 5KVA online UPS for critical power backup. Pure sine wave output with zero transfer time.', specifications: { 'Capacity': '5KVA / 4KW', 'Input Voltage': '160-280V AC', 'Output Voltage': '220V ± 1%', 'Battery': '12V x 8', 'Transfer Time': '0ms', 'Warranty': '2 Years' }, images: ['/placeholder.svg'], is_featured: true, is_active: true },
  { id: '2', name: 'TPC 10KVA Servo Stabilizer', slug: 'tpc-10kva-servo-stabilizer', category: 'servo-stabilizers', price: 45000, sale_price: null, stock: 25, description: 'Industrial grade servo voltage stabilizer for precise voltage regulation. Ideal for CNC machines and sensitive equipment.', specifications: { 'Capacity': '10KVA', 'Input Range': '150-260V AC', 'Output': '220V ± 1%', 'Type': 'Servo Motor Controlled', 'Warranty': '2 Years' }, images: ['/placeholder.svg'], is_featured: true, is_active: true },
  { id: '3', name: 'TPC 25KVA Distribution Transformer', slug: 'tpc-25kva-transformer', category: 'transformers', price: 250000, sale_price: 225000, stock: 5, description: 'Oil-cooled distribution transformer for commercial and industrial applications. Built to NEA standards.', specifications: { 'Capacity': '25KVA', 'Primary': '11KV', 'Secondary': '400/230V', 'Cooling': 'Oil Cooled (ONAN)', 'Standard': 'IS 1180', 'Warranty': '5 Years' }, images: ['/placeholder.svg'], is_featured: true, is_active: true },
  { id: '4', name: 'TPC 2HP VFD Drive', slug: 'tpc-2hp-vfd-drive', category: 'vfd-drives', price: 18500, sale_price: null, stock: 30, description: 'Variable frequency drive for precise motor speed control. Energy efficient with built-in PID controller.', specifications: { 'Power': '2HP / 1.5KW', 'Input': '220V Single Phase', 'Output': '3 Phase', 'Frequency': '0-400Hz', 'Protection': 'IP20', 'Warranty': '1 Year' }, images: ['/placeholder.svg'], is_featured: true, is_active: true },
  { id: '5', name: 'TPC 1KVA Home Inverter', slug: 'tpc-1kva-home-inverter', category: 'home-inverters', price: 12000, sale_price: 9999, stock: 50, description: 'Pure sine wave home inverter for reliable backup power. Powers TV, fan, lights and more.', specifications: { 'Capacity': '1KVA / 800W', 'Output': 'Pure Sine Wave', 'Battery': '12V', 'Charging': '10A', 'Display': 'LED', 'Warranty': '2 Years' }, images: ['/placeholder.svg'], is_featured: true, is_active: true },
  { id: '6', name: 'TPC 50A Battery Charger', slug: 'tpc-50a-battery-charger', category: 'battery-chargers', price: 28000, sale_price: null, stock: 20, description: 'Industrial battery charger with automatic cut-off. Suitable for all lead-acid batteries.', specifications: { 'Current': '50A', 'Voltage': '12/24/48V Selectable', 'Type': 'SMPS Based', 'Protection': 'Over Charge, Short Circuit', 'Warranty': '1 Year' }, images: ['/placeholder.svg'], is_featured: true, is_active: true },
  { id: '7', name: 'TPC 3KW Solar Inverter System', slug: 'tpc-3kw-solar-system', category: 'solar-solutions', price: 350000, sale_price: 315000, stock: 8, description: 'Complete 3KW on-grid solar system with panels, inverter and installation. Save on electricity bills.', specifications: { 'Capacity': '3KW', 'Panels': '6 x 500W Mono', 'Inverter': 'Hybrid', 'Battery': 'Optional', 'Annual Generation': '~4500 kWh', 'Warranty': 'Panels 25 Years, Inverter 5 Years' }, images: ['/placeholder.svg'], is_featured: true, is_active: true },
  { id: '8', name: 'TPC 200Ah Tubular Battery', slug: 'tpc-200ah-tubular-battery', category: 'batteries', price: 32000, sale_price: null, stock: 40, description: 'Long-life tubular battery for UPS and inverter systems. Deep cycle design for reliable backup.', specifications: { 'Capacity': '200Ah', 'Voltage': '12V', 'Type': 'Tubular Lead Acid', 'Life': '5-7 Years', 'Warranty': '3+2 Years' }, images: ['/placeholder.svg'], is_featured: true, is_active: true },
  { id: '9', name: 'TPC ARC 250 Welding Machine', slug: 'tpc-arc-250-welding', category: 'welding-machines', price: 15000, sale_price: 12500, stock: 35, description: 'IGBT inverter-based welding machine. Lightweight, portable with high duty cycle.', specifications: { 'Current': '20-250A', 'Duty Cycle': '60% at 250A', 'Input': '220V', 'Type': 'IGBT Inverter', 'Weight': '5.5 Kg', 'Warranty': '1 Year' }, images: ['/placeholder.svg'], is_featured: false, is_active: true },
  { id: '10', name: 'TPC 100A Thyristor Rectifier', slug: 'tpc-100a-rectifier', category: 'rectifiers', price: 65000, sale_price: null, stock: 10, description: 'SCR-based rectifier for electroplating and industrial DC applications.', specifications: { 'Current': '100A', 'Output Voltage': '0-50V DC', 'Regulation': '± 1%', 'Cooling': 'Forced Air', 'Warranty': '2 Years' }, images: ['/placeholder.svg'], is_featured: false, is_active: true },
  { id: '11', name: 'TPC Power Distribution Panel', slug: 'tpc-power-distribution-panel', category: 'panel-boards', price: 120000, sale_price: null, stock: 12, description: 'Custom MCC and PCC panel boards for industrial power distribution. Built to IS standards.', specifications: { 'Type': 'MCC/PCC', 'Voltage': '415V', 'Current': 'Up to 800A', 'Enclosure': 'IP54', 'Standard': 'IS 8623', 'Warranty': '2 Years' }, images: ['/placeholder.svg'], is_featured: false, is_active: true },
  { id: '12', name: 'TPC 5KVA Relay Stabilizer', slug: 'tpc-5kva-relay-stabilizer', category: 'relay-stabilizers', price: 8500, sale_price: 6999, stock: 60, description: 'Economical relay-type voltage stabilizer for home appliances. Protects AC, TV, fridge from voltage fluctuations.', specifications: { 'Capacity': '5KVA', 'Input Range': '140-280V', 'Output': '220V ± 8%', 'Type': 'Relay Switching', 'Display': 'Digital', 'Warranty': '1 Year' }, images: ['/placeholder.svg'], is_featured: true, is_active: true },
];

export const sampleAnnouncements = [
  { id: '1', text_en: '🔥 Dashain Special — Up to 20% off UPS Systems!', text_np: '🔥 दशैं विशेष — UPS मा २०% छुट!', is_active: true, display_order: 1 },
  { id: '2', text_en: '🚚 Free delivery on orders above Rs. 50,000', text_np: '🚚 रु. ५०,००० माथिको अर्डरमा निःशुल्क डेलिभरी', is_active: true, display_order: 2 },
  { id: '3', text_en: '📞 Expert engineers available 7 days a week', text_np: '📞 विशेषज्ञ इन्जिनियरहरू हप्ताको ७ दिन उपलब्ध', is_active: true, display_order: 3 },
];

export const sampleReviews = [
  { id: '1', product_id: '1', customer_name: 'Rajesh Sharma', customer_city: 'Kathmandu', rating: 5, message: 'Excellent UPS system! Has been running my office for 2 years without any issues. Great after-sales support from TPC team.', is_approved: true },
  { id: '2', product_id: '5', customer_name: 'Sita Gurung', customer_city: 'Pokhara', rating: 4, message: 'Very good home inverter. Silent operation and provides clean power for our home appliances.', is_approved: true },
  { id: '3', product_id: '3', customer_name: 'Hari Bahadur Thapa', customer_city: 'Biratnagar', rating: 5, message: 'TPC installed a 25KVA transformer for our factory. Professional service and quality product. Highly recommended!', is_approved: true },
];

export const sampleFAQs = [
  { id: '1', question_en: 'Do you deliver across Nepal?', question_np: 'के तपाईंहरू नेपालभरि डेलिभरी गर्नुहुन्छ?', answer_en: 'Yes! We deliver to all 77 districts of Nepal. Delivery charges vary by location. Orders above Rs. 50,000 qualify for free delivery.', answer_np: 'हो! हामी नेपालका सबै ७७ जिल्लामा डेलिभरी गर्छौं। डेलिभरी शुल्क स्थान अनुसार फरक हुन्छ। रु. ५०,००० माथिको अर्डरमा निःशुल्क डेलिभरी।', category: 'Delivery', is_visible: true, display_order: 1 },
  { id: '2', question_en: 'What warranty do your products come with?', question_np: 'तपाईंहरूका उत्पादनहरूमा कस्तो वारेन्टी छ?', answer_en: 'Warranty varies by product — from 1 year to 5 years. All warranties cover manufacturing defects. Extended warranty available on select products.', answer_np: 'वारेन्टी उत्पादन अनुसार फरक हुन्छ — १ वर्षदेखि ५ वर्षसम्म।', category: 'Warranty & Repair', is_visible: true, display_order: 2 },
  { id: '3', question_en: 'Can I get a custom transformer built?', question_np: 'के म कस्टम ट्रान्सफर्मर बनाउन सक्छु?', answer_en: 'Absolutely! We manufacture custom transformers to your exact specifications. Contact us with your requirements for a quote.', answer_np: 'अवश्य! हामी तपाईंको आवश्यकता अनुसार कस्टम ट्रान्सफर्मर बनाउँछौं।', category: 'Products', is_visible: true, display_order: 3 },
  { id: '4', question_en: 'Which payment methods do you accept?', question_np: 'कुन भुक्तानी विधिहरू स्वीकार गर्नुहुन्छ?', answer_en: 'We accept Khalti, eSewa, IME Pay, and Cash on Delivery (COD). Digital payments are processed securely.', answer_np: 'हामी खल्ती, eSewa, IME Pay, र क्यास अन डेलिभरी (COD) स्वीकार गर्छौं।', category: 'Payment', is_visible: true, display_order: 4 },
  { id: '5', question_en: 'How do I book a repair?', question_np: 'म कसरी मर्मत बुक गर्छु?', answer_en: 'Visit our Repair Booking page or call us directly. Our engineers will schedule a visit at your convenience.', answer_np: 'हाम्रो मर्मत बुकिंग पेजमा जानुहोस् वा सिधै कल गर्नुहोस्।', category: 'Warranty & Repair', is_visible: true, display_order: 5 },
];

export const sampleBlogPosts = [
  { id: '1', title: 'How to Choose the Right UPS for Your Home', slug: 'how-to-choose-right-ups', content: '<h2>Understanding UPS Systems</h2><p>A UPS (Uninterruptible Power Supply) is essential for protecting your electronic devices from power outages and voltage fluctuations common in Nepal...</p><p>When choosing a UPS for your home, consider: the total wattage of devices you want to back up, the desired backup time, and the type of UPS (offline, line-interactive, or online).</p><h3>Types of UPS</h3><p><strong>Offline UPS:</strong> Basic protection, suitable for desktop computers. Transfer time of 5-12ms.</p><p><strong>Line-Interactive UPS:</strong> Better voltage regulation with built-in AVR. Ideal for most homes.</p><p><strong>Online UPS:</strong> Zero transfer time, best for critical equipment. Recommended for servers and medical equipment.</p>', thumbnail_url: '/placeholder.svg', category: 'Product Guides', tags: ['UPS', 'Home', 'Guide'], meta_title: 'How to Choose the Right UPS - TPC Power Solutions', meta_description: 'Complete guide to choosing the right UPS system for your home in Nepal.', is_published: true, created_at: '2025-12-15' },
  { id: '2', title: 'Solar Energy in Nepal: A Complete Guide for 2026', slug: 'solar-energy-nepal-2026', content: '<h2>Nepal Solar Revolution</h2><p>Nepal receives abundant sunlight, making it an ideal location for solar energy. With rising electricity costs and frequent load shedding, solar systems offer a reliable and cost-effective alternative...</p><p>The government of Nepal offers subsidies for solar installations, making it more affordable than ever.</p><h3>Types of Solar Systems</h3><p><strong>On-Grid:</strong> Connected to the national grid, excess power can be sold back.</p><p><strong>Off-Grid:</strong> Independent system with battery storage, ideal for remote areas.</p><p><strong>Hybrid:</strong> Combines both, offering maximum flexibility and reliability.</p>', thumbnail_url: '/placeholder.svg', category: 'Nepal Energy News', tags: ['Solar', 'Nepal', 'Green Energy'], meta_title: 'Solar Energy in Nepal 2026 - TPC Power Solutions', meta_description: 'Complete guide to solar energy solutions in Nepal for homes and businesses.', is_published: true, created_at: '2026-01-20' },
];
